### ISSUE TITLE
Unable to download model files

### ISSUE THREAD

**Issue by raghuk-botaiml** [AI4Bharat/indicTrans#10]
I am the error below when trying to download the models:
![model-download-error](https://user-images.githubusercontent.com/64590389/121365915-ace52180-c956-11eb-91fc-a706d4620308.png)

Could you please upload the models to alternative services and provide the links?

**Comment by gowtham1997** [comment]
@raghuk-botaiml Thanks for letting us know. 

You can download the models from these links:
[indic-en](https://storage.googleapis.com/samanantar-public/V0.2/models/indic-en.zip)
[en-indic](https://storage.googleapis.com/samanantar-public/V0.2/models/en-indic.zip)

Will update the readme and colab.

**Comment by raghuk-botaiml** [comment]
@gowtham1997 thanks for the quick response. I will leave this issue open, so that you can close it once you update readme and colab.

**Comment by gowtham1997** [comment]
Added pull request, should be merged soon
