### ISSUE TITLE
problems with downloading the model

### ISSUE THREAD

**Issue by leonovaAnya** [AI4Bharat/indicTrans#19]
Hello, cannot download indic-en model, Could you, please, upload it

**Comment by gowtham1997** [comment]
hey,
we are having some problems with GCP where we host our models. 
We will have a temporary download link ready in sometime and let you know

**Comment by deepanshusachdeva5** [comment]
Is there any update on the issue?

**Comment by TarunTater** [comment]
hi @gowtham1997, any luck with hosting the models? we are trying to run an experiment for a conference and wanted to include this model.

**Comment by gowtham1997** [comment]
Hey guys, 

This issue has been resolved

**Comment by TarunTater** [comment]
@gowtham1997 - able to download the models now. thanks

**Comment by leonovaAnya** [comment]
@gowtham1997  thanks a lot, everything's ok
