### ISSUE TITLE
Indic-Eng model error while parsing long sentence

### ISSUE THREAD

**Issue by suvanbalu** [AI4Bharat/indicTrans#21]
"(indic2en_model.batch_translate(ta_sent, 'ta', 'en')"

While passing Tamil sentence of length more than 723 we get a error 

'''num_words = len(sent.split())
     61         if num_words > MAX_SEQ_LEN:
---> 62             print_str = " ".join(num_words[:5]) + " .... " + " ".join(num_words[-5:])
     63             sent = " ".join(num_words[:MAX_SEQ_LEN])
     64             print(

TypeError: 'int' object is not subscriptable'''

Instead of sent.split() there is num.words which is an integer and not subscriptable

**Comment by gowtham1997** [comment]
Added a pull request for the fix. It will be merged soon

Thanks for pointing this out

**Comment by suvanbalu** [comment]
Ya thanks
