### ISSUE TITLE
ImportError: cannot import name 'convert_namespace_to_omegaconf' from 'fairseq.dataclass.utils' 

### ISSUE THREAD

**Issue by snehampatil** [AI4Bharat/indicTrans#29]
I am trying to run the translation code in my IDE.  The python code is placed under indicTrans folder.  
The statement 
`from inference.engine import Model `
throws an error :
```Traceback (most recent call last):  
  File "Run.py", line 1, in <module>  
    from inference.engine import Model  
  File "/home/sneha/Documents/indic/indicTrans/inference/engine.py", line 15, in <module>  
    from inference.custom_interactive import Translator  
  File "/home/sneha/Documents/indic/indicTrans/inference/custom_interactive.py", line 17, in <module>  
    from fairseq.dataclass.utils import convert_namespace_to_omegaconf  
ImportError: cannot import name 'convert_namespace_to_omegaconf' from 'fairseq.dataclass.utils' (/home/sneha/.local/lib/python3.8/site-packages/fairseq/dataclass/utils.py)
```

May I know how this can be solved ?  
Thank you

**Comment by soumendrak** [comment]
@snehampatil ,
Which documentation are you following? Did you git clone `fairseq`?

**Comment by snehampatil** [comment]
Import Statement : `from inference.engine import Model `   

I followed the installation steps mentioned in the Colab Notebook. And I have cloned the `fairseq`  
`git clone https://github.com/pytorch/fairseq.git`

**Comment by gowtham1997** [comment]
Sorry for the late reply. 

I just tested our[ tutorial colab notebook](https://colab.research.google.com/github/AI4Bharat/indicTrans/blob/main/indicTrans_python_interface.ipynb#scrollTo=yTnWbHqY01-B) with the latest fairseq and didn't face this error. 
![image](https://user-images.githubusercontent.com/9641196/146648138-57e4ac94-1827-41f4-8d9a-c7924924dd33.png)

You can double-check the fairseq installation in your local(see if you have another old fairseq that your python is using as default, etc) or help us with a reproducible colab script.

**Comment by volcas** [comment]
The issue has come back. Tested on the tutorial nb too. Can anyone help resolve it?
