### ISSUE TITLE
Unable to access models

### ISSUE THREAD

**Issue by sugeeth14** [AI4Bharat/indicTrans#31]
Hello, I am trying to use the pre-trained models and I am unable to download them with the error as attached below.
<img width="1440" alt="Screen Shot 2022-01-02 at 11 54 31 PM" src="https://user-images.githubusercontent.com/22686557/147905627-f0768c0e-ad41-4312-90ab-c9f85170bf90.png">

At the same time in the demo [colab notebook](https://colab.research.google.com/github/AI4Bharat/indicTrans/blob/main/indicTrans_python_interface.ipynb) while trying to run the imports cell, I encounter the following error. I restarted the run time but not sure why this is occurring.
<img width="1384" alt="Screen Shot 2022-01-02 at 11 56 46 PM" src="https://user-images.githubusercontent.com/22686557/147905966-d427f359-a8a6-422e-8baa-a6c32e516d6f.png">

 I could run the same notebook previously without any issues I tried to use an older commit version of fairseq from [here](https://github.com/pytorch/fairseq/commit/a54021305d6b3c4c5959ac9395135f63202db8f1) in that case I encounter the same error as above. Not sure if this is a problem with fairseq or something else.  

When I tried to `pip install fairseq` instead of using the source repository I could move forward without the import issue but still the models are not available.
Let me know how I can fix this and if I am missing anything.
Thank you.

**Comment by gowtham1997** [comment]
Yes, the models are not accessible due to some GCP billing issues. It might take some days for this to get resolved.

As a temporary workaround, we are planning to host the models in google drive; we will let you know once this is done

**Comment by sumanthd17** [comment]
Hi @sugeeth14 Thanks for your patience. Please use the [gdrive](https://drive.google.com/drive/folders/1bfF2m1UzzNe_M9SB6M60BfQeTsx4zq5j?usp=sharing) link to download the models.

Thanks

**Comment by gowtham1997** [comment]
The links have started working now
