### ISSUE TITLE
Demo Colab notebook issue.

### ISSUE THREAD

**Issue by sugeeth14** [AI4Bharat/indicTrans#32]
Hello I am trying to run the demo [colab notebook](https://colab.research.google.com/github/AI4Bharat/indicTrans/blob/main/indicTrans_python_interface.ipynb) but when I try to import the fairseq dependencies I am getting the below error. 

I tried restarting the runtime as mentioned, installed fairseq using pip, and also tried a different checkout version of faireq from [here](https://github.com/pytorch/fairseq/commit/da9eaba12d82b9bfc1442f0e2c6fc1b895f4d35d) and [here](https://github.com/pytorch/fairseq/commit/a54021305d6b3c4c5959ac9395135f63202db8f1) but still no help. 

Not sure if I am missing something. Attaching the screenshot for reference. Kindly help.
<img width="1100" alt="Screen Shot 2022-01-08 at 2 42 14 AM" src="https://user-images.githubusercontent.com/22686557/148639631-936ec10b-1b1b-4294-8ed6-6c04d084285d.png">

P.S: When installing with pip I am not getting this error but another error as attached below when trying to import indic trans `Model`

<img width="969" alt="Screen Shot 2022-01-08 at 2 45 27 AM" src="https://user-images.githubusercontent.com/22686557/148639724-e8f0f4bf-3f36-4d7c-bddf-5b830080ba0a.png">

**Comment by gowtham1997** [comment]
The main problem seems to be with the installation of fairseq on colab. 
On colab, this error isn't deterministic, I can sometimes install fairseq properly without any error (see the picture which i ran sometime back) and most of the times, it doesn't work.
![image](https://user-images.githubusercontent.com/9641196/148822097-6124c96f-1d27-4c81-a909-b9d196357a58.png)


For the second error, you can do:
```python
#cd into indicTrans before this
from inference.engine import Model

indic2en_model = Model(expdir='../indic-en')
```

^ this should solve the import errors but still get you into fairseq errors on colab. It will work on your local or other GPU systems if fairseq is installed.


I will update if i find a way to install fairseq without the import errors on colab.

**Comment by sugeeth14** [comment]
Thank you @gowtham1997 for the update. I will also try to see if I can fix it anyway and update you.

**Comment by gowtham1997** [comment]
This is fixed now.
please use the latest python inference colab to test it and let us know if it works 

Thanks

**Comment by sugeeth14** [comment]
Yes, it works, thank you for the update.
