### ISSUE TITLE
Inappropriate hindi transliteration

### ISSUE THREAD

**Issue by Sonali210** [AI4Bharat/indicTrans#33]
Code:
```
from indicnlp.transliterate.unicode_transliterate import ItransTransliterator
from indicnlp import loader
from indicnlp import common
common.set_resources_path(INDIC_RESOURCES_PATH)
loader.load()
ItransTransliterator.to_itrans('मैं आज आपकी किस प्रकार सहायता कर सकता हूँ?', 'hi')
```
Output:
```
mai.m aaja aapakii kisa prakaara sahaayataa kara sakataa huuँ?
```
[Output using google translator](https://www.google.com/search?q=online+google+translator&rlz=1C1ONGR_enIN977IN977&oq=online+googl&aqs=chrome.1.69i57j69i59j0i512l3j0i433i512j0i512l4.3808j0j7&sourceid=chrome&ie=UTF-8):

jaanakar achchha laga. main aaj aapakee kis prakaar sahaayata kar sakata hoon?

There is unnecessary use of '.' and 'uँ' in romanization. What can be the best solution that gives appropriate and presentable transliterated output.

**Comment by gowtham1997** [comment]
Thanks for letting us know.

Since this is a transliteration issue that is not related to the IndicTrans model (which is a translation system). Can you please open this issue at [indicnlp](https://github.com/anoopkunchukuttan/indic_nlp_library) library repo instead?
