### ISSUE TITLE
Can't download the model ...showing error

### ISSUE THREAD

**Issue by MdYeasinSamadArnob** [AI4Bharat/indicTrans#34]
The download link not working

**Comment by gowtham1997** [comment]
Please use this temporary [gdrive](https://drive.google.com/drive/folders/1bfF2m1UzzNe_M9SB6M60BfQeTsx4zq5j?usp=sharing) link to download the models.

**Comment by Yagna24** [comment]
Do you have any pretrained models on hugging face that could be exported like this  ? 
tokenizer = Wav2Vec2Tokenizer.from_pretrained("           ")
model = Wav2Vec2ForCTC.from_pretrained("   ")

**Comment by bil-ash** [comment]
The google drive link has only the en2indic and the indic2en model. From where can I download the indic2indic model? @gowtham1997
