### ISSUE TITLE
Mixed language translation issue

### ISSUE THREAD

**Issue by ayushbits** [AI4Bharat/indicTrans#35]
Hi,

When I translate a source sentence containing mix of English and Hindi words into target language **Hindi**, random words appear for Hindi words.
For eg.

> High Commission of India,
> India House,
> माझगाव डॉक शिपबिल्डर्स लिमिटेड
> Mazagon Dock Shipbuilders Limited

Corresponding Hindi Translation

> भारतीय उच्चायोग,
> इंडिया हाउस,
> एक्सरसाइज एक्सरसाइज एक्सरसाइज एक्सरसाइज एक्सरसाइज एक्सरसाइज एक्सरसाइज एक्सरसाइज एक्सरसाइज एक्सरसाइज एक्सरसाइज एक्सरसाइज एक्सरसाइज एक्सरसाइज एक्सरसाइज एक्सरसाइज एक्सरसाइज एक्सरसाइज एक्सरसाइज एक्सरसाइज एक्सरसाइज एक्सरसाइज एक्सरसाइज एक्सरसाइज एक्सरसाइज एक्सरसाइज एक्सरसाइज एक्सरसाइज एक्सरसाइज एक्सरसाइज एक्सरसाइज एक्सरसाइज एक्सरसाइज एक्सरसाइज एक्सरसाइज एक्सरसाइज एक्सरसाइज एक्सरसाइज एक्सरसाइज एक्सरसाइज एक्सरसाइज एक्सरसाइज एक्सरसाइज एक्सरसाइज एक्सरसाइज एक्सरसाइज एक्सरसाइज
> मझगांव डॉक शिपबिल्डर्स लिमिटेड

I used joint_translate.sh script for translation.

Thanks

**Comment by gowtham1997** [comment]
The model hasn't been trained/tested with code-mixed data. So this noisy output is sort of expected. 

If the English words are named entities, you can try to transliterate them to hindi script (so that the full sentence is in hindi) and try again.
