### ISSUE TITLE
TypeError: Descriptors cannot not be created directly while importing indicTrans

### ISSUE THREAD

**Issue by AbhijitManepatil** [AI4Bharat/indicTrans#37]
While referring to the jupyter notebook [here](https://colab.research.google.com/github/AI4Bharat/indicTrans/blob/main/indicTrans_python_interface.ipynb)

`from indicTrans.inference.engine import Model `

will get the following issue
```
TypeError: Descriptors cannot not be created directly.
If this call came from a _pb2.py file, your generated code is out of date and must be regenerated with protoc >= 3.19.0.
If you cannot immediately regenerate your protos, some other possible workarounds are:
 1. Downgrade the protobuf package to 3.20.x or lower.
 2. Set PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python (but this will use pure-Python parsing and will be much slower).
```
may I know possible solution for this issue,
Thanks

**Comment by gowtham1997** [comment]
![image](https://user-images.githubusercontent.com/9641196/172230080-e6bed20d-6e32-4e68-af67-5b36f4debfb9.png)
I just reran the colab notebook and it was working as expected.

Perhaps, there was some change 3 days ago in fairseq that could've caused this, but looks like its fixed now.

Please reopen the issue if you are still facing errors

**Comment by AbhijitManepatil** [comment]
> ![image](https://user-images.githubusercontent.com/9641196/172230080-e6bed20d-6e32-4e68-af67-5b36f4debfb9.png) I just reran the colab notebook and it was working as expected.
> 
> Perhaps, there was some change 3 days ago in fairseq that could've caused this, but looks like its fixed now.
> 
> Please reopen the issue if you are still facing errors

Thanks resolved now.
