### ISSUE TITLE
ULCA API Help

### ISSUE THREAD

**Issue by AbhijitManepatil** [AI4Bharat/indicTrans#38]
Hi,
As I am looking to use ULCA API for Indian Language translation, I explore through the Bhashini platform. [Bhashini](https://bhashini.gov.in/ulca)
I checked with ULCA API with this [link](https://app.swaggerhub.com/apis/ulca/ULCA/0.7.0) for different models but I was not able to find proper documentation on those API call-in details or some Sample examples. although the work done on this platform is extremely useful, If you can help to understand those APIs with some documentation or simple examples that will be more fruitful, especially since I am looking into Translations API.

Thanks

**Comment by gowtham1997** [comment]
I don't have enough knowledge to help you with this. 

You can perhaps try opening this issue on [ULCA github ](https://github.com/ULCA-IN/ulca). Some of the authors there are aware of IndicTrans and might be able to help out more
