### ISSUE TITLE
Don't want particular keywords to translate in message

### ISSUE THREAD

**Issue by drone1111** [AI4Bharat/indicTrans#39]
Have a list of words that I want to keep as it is when translating from one language to another. How to achieve this.

**Comment by gowtham1997** [comment]
It sounds like you want to do [constrained decoding](https://github.com/facebookresearch/fairseq/tree/main/examples/constrained_decoding). Fairseq does support it and you can read more on the hyperlink.

`joint_translate.sh` is based on fairseq-interactive (command-line interface for translation). You can refer to the hyperlink and try adding some constraints [here](https://github.com/AI4Bharat/indicTrans/blob/17c6838f63f8574421e36f52e467f668b9caf1b5/joint_translate.sh#L44-L51) to see if that helps.

I am closing this issue as it's not an issue related to the current repo/code but enquiring about features of fairseq. 

Please let us know if you get good results.
