### ISSUE TITLE
Dataset not available

### ISSUE THREAD

**Issue by anirudhv14** [AI4Bharat/indicTrans#40]
The datasets in the google storage api, shows a 403 error. 
"https://storage.googleapis.com/samanantar-public/V0.2/data/en2indic/samanatar-en-indic-v0.2.zip" & "https://storage.googleapis.com/samanantar-public/benchmarks.zip".
How to get the following datasets now?

**Comment by sumanthd17** [comment]
Please use the mirror links available [here](https://indicnlp.ai4bharat.org/samanantar/)

Alternatively, you can download from [Huggingface Datasets](https://huggingface.co/datasets/ai4bharat/samanantar)

**Comment by anirudhv14** [comment]
Yes, but here also the benchmarks.zip is not available.

**Comment by sumanthd17** [comment]
It is now added to the website, you can download from [here](https://indicnlp.ai4bharat.org/samanantar/#mirror-links)
