### ISSUE TITLE
Handling of URL in source sentence

### ISSUE THREAD

**Issue by drone1111** [AI4Bharat/indicTrans#41]
Hi, sentences having URL doesn't get translated correctly,
Input: If you develop these symptoms in someone close to you, staying at home can help prevent the spread of Coronavirus infection. For details visit https://mohfw.gov.in/
Output (Hindi): यदि आप अपने किसी करीबी में ये लक्षण विकसित करते हैं, तो घर पर रहना कोरोना वायरस संक्रमण के प्रसार को रोकने में मदद कर सकता है। अधिक जानकारी के लिए https:// www. mohfw. gov. in/pdf पर जाएं। //mohfw. gov. in/पर उपलब्ध है।

How to handle it?

**Comment by gowtham1997** [comment]
One way to handle this is use a regex for URLs and replace with word like website:

If you develop these symptoms in someone close to you, staying at home can help prevent the spread of Coronavirus infection. For details, visit website

यदि आप अपने किसी करीबी में ये लक्षण विकसित करते हैं, तो घर पर रहना कोरोना वायरस संक्रमण के प्रसार को रोकने में मदद कर सकता है। अधिक जानकारी के लिए वेबसाइट देखें

And replace "वेबसाइट" in Hindi translation with the url

This might not be foolproof, you can try with other approaches (ie better replacement words/patterns) and let us know what worked best for you.
