### ISSUE TITLE
ModuleNotFoundError: No module named 'inference'

### ISSUE THREAD

**Issue by MdYeasinSamadArnob** [AI4Bharat/indicTrans#45]
Throwing error 

from indicTrans.inference.engine import Model

showing
---------------------------------------------------------------------------
ModuleNotFoundError                       Traceback (most recent call last)
~\AppData\Local\Temp/ipykernel_1140/1581464475.py in <module>
----> 1 from indicTrans.inference.engine import Model

D:\datascienceprojects\project-new\indicTrans\inference\engine.py in <module>
     13 from indicnlp.tokenize import sentence_tokenize
     14 
---> 15 from inference.custom_interactive import Translator
     16 
     17 

ModuleNotFoundError: No module named 'inference'

**Comment by eldhoittangeorge** [comment]
> Throwing error
> 
> from indicTrans.inference.engine import Model
> 
> ## showing
> ModuleNotFoundError Traceback (most recent call last) ~\AppData\Local\Temp/ipykernel_1140/1581464475.py in ----> 1 from indicTrans.inference.engine import Model
> 
> D:\datascienceprojects\project-new\indicTrans\inference\engine.py in 13 from indicnlp.tokenize import sentence_tokenize 14 ---> 15 from inference.custom_interactive import Translator 16 17
> 
> ModuleNotFoundError: No module named 'inference'

Try importing after running `%cd indicTrans`
