### ISSUE TITLE
Can we host the model on Non GPU system?

### ISSUE THREAD

**Issue by mehul-rigyn** [AI4Bharat/indicTrans#51]
Will the model perform if hosted on a non GPU system?

**Comment by mediocremonke** [comment]
> Will the model perform if hosted on a non GPU system?

Yes it can work on non GPU System

**Comment by sumanthd17** [comment]
I would be possible, but not practical to use. The predictions will be incredibly slow on a CPU machine. We recommend using a GPU. Anything with 16GB capacity should do the job

**Comment by arnavmehta7** [comment]
It even works on 4gb GPU :)
